[package]
name = "supra-exercise"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.37", features = ["macros", "sync", "rt", "time"] }
futures = "0.3"
anyhow = "1.0"
async-trait = "0.1"
